# frozen_string_literal: true

module Engine
  module Game
    module G1890
      module Entities
        COMPANIES = [
          {
            name: '有馬鉄道',
            value: 20,
            revenue: 5,
            desc: "配置制限:有馬(D7) \n 企業に売られたら有馬にタイル配置",
            sym: '有電',
            type: :private,
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', remove: '4', hexes: ['D7'] },
                        {
                          type: 'tile_lay',
                          hexes: ['D7'],
                          tiles: %w[3 4 58],
                          when: 'sold',
                          owner_type: 'corporation',
                          count: 1,
                        }],
            color: nil,
          },
          {
            name: '神戸市電',
            value: 40,
            revenue: 10,
            desc: '配置制限:神戸(F5)',
            sym: '神電',
            type: :private,
            abilities: [
              { type: 'blocks_hexes', owner_type: 'player', remove: '4', hexes: ['F5'] },
              { type: 'revenue_change', revenue: 5, on_phase: '4' },
            ],
            color: nil,
          },
          {
            name: '阪堺電鉄',
            value: 70,
            revenue: 15,
            desc: '配置制限:堺(J11)大阪南(I12) \n 第4フェイズ(5列車購入時)に閉鎖しない　ただし収入は5になり、売却できず、株券枚数制限に含み続ける',
            sym: '堺電',
            type: :private,
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', remove: '4', hexes: %w[I12 J11] },
                        { type: 'close', on_phase: 'never' },
                        {
                          type: 'revenue_change',
                          revenue: 5,
                          on_phase: '4',
                        }],
            color: nil,
          },
          {
            name: '阪神国道軌道',
            value: 110,
            revenue: 20,
            desc: '配置制限なし　阪神電鉄の株券1株が付属',
            sym: '阪国',
            type: :private,
            abilities: [{ type: 'shares', shares: '阪神_1' }],
            color: nil,
          },
          {
            name: '京津鉄道',
            value: 160,
            revenue: 25,
            desc: "配置制限:京都(B17)京都の東(B19) \n 京阪電鉄の株券1株が付属",
            sym: '京津',
            type: :private,
            abilities: [
              { type: 'blocks_hexes', owner_type: 'player', remove: '4', hexes: %w[B17 B19] },
              { type: 'shares', shares: '京阪_1' }
            ],
            color: nil,
          },
          {
            name: '大阪市電',
            value: 220,
            revenue: 40,
            desc: '配置制限:大阪北(G12)大阪西(H11)大阪東(H13)  '\
                  '購入プレーヤーは大阪地下鉄の株価を設定し、社長株を受け取ります。'\
                  '大阪地下鉄が設立されても、列車を購入しなければ、大阪市電は閉鎖されず、大阪地下鉄は、配当を受け続けることができます。'\
                  'しかし、大阪地下鉄は、運営ラウンドの自社の手番で無配を繰り返すため、株価は下がり続けます。'\
                  '大阪地下鉄の最初の手番がくれば、大阪市内の3ヘックスへのタイルの置き換えは、自由になるものとします。'\
                  '大阪地下鉄が列車を購入すると大阪市電は閉鎖されます。この個人会社は、公共会社が購入することが出来ません。',
            abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: %w[G12 H11 H13] },
                        { type: 'close', when: 'bought_train', corporation: 'メトロ' },
                        { type: 'no_buy' },
                        { type: 'shares', shares: 'メトロ_0' }
                      ],
            sym: '市電',
            type: :private,
            color: nil,
          },
          {
            name: '京福鉄道',
            value: 200,
            revenue: 40,
            desc: '京阪が京都に駅トークンを置いたとき、京阪の金庫にも毎運営時に¥40入ります。',
            sym: '京福',
            type: :latecomer,
            abilities: [{ type: 'close', on_phase: 'never', owner_type: 'player' },
                        { type: 'no_buy', owner_type: 'player' },
                        ],
            color: nil,
          },
          {
            name: '神戸高速鉄道', # TODO: 盤面上の特殊トークン表示は未実装
            value: 240,
            revenue: 0,
            desc: '神戸を収益に使う会社ごとに、神戸高速鉄道はその神戸収益の半額を受け取ります。',
            sym: '神高',
            type: :latecomer,
            abilities: [{ type: 'close', on_phase: 'never', owner_type: 'player' },
                        { type: 'no_buy', owner_type: 'player' },
                        ],
            color: nil,
          },
          {
            name: '北大阪急行',
            value: 280,
            revenue: 60,
            desc: '最初の6列車が買われた次の運行ラウンドに一回だけ、大阪万国博覧会で特別収入として通常の配当に¥40 を加算し(¥100) 受け取ります。',
            sym: '北急',
            type: :latecomer,
            abilities: [{ type: 'close', on_phase: 'never', owner_type: 'player' },
                        { type: 'no_buy', owner_type: 'player' },
                        ],
            color: nil,
          },
          {
            name: '泉北高速鉄道',
            value: 320,
            revenue: 70,
            desc: '堺に駅トークンを配置している公共会社の金庫に、毎運営時に¥40入ります。',
            sym: '泉北',
            type: :latecomer,
            abilities: [{ type: 'close', on_phase: 'never', owner_type: 'player' },
                        { type: 'no_buy', owner_type: 'player' },
                        ],
            color: nil,
          },
          {
            name: '河南鉄道',
            value: 100,
            revenue: 0,
            desc: '第2フェイズから、近鉄への合併が可能になります。第3フェイズになると、近鉄に強制合併されます。'\
                  '近鉄の10%株に引き替えて閉鎖します。閉鎖時に現金の半分(端数切り上げ)と列車を近鉄が引き取ります。残りの現金を社長に払い戻します。',
            sym: '河南',
            type: :minor,
            abilities: [{ type: 'no_buy', owner_type: 'player' },
                        { type: 'exchange',
                          corporations: ['近鉄'],
                          when: 'or_between_turns',
                          from: 'reserved'},
                       ],
            color: nil,
          },
          {
            name: '大阪電気軌道',
            value: 200,
            revenue: 0,
            desc: '大阪電気軌道は、近鉄の前身となった会社です。初期株式ラウンドで購入されたとき、近鉄の株価を決定します。'\
                  '近鉄の社長株 (20%)に引き替えて閉鎖します。近鉄はこの2株で設立されます。全資産を近鉄が引き継ぎます。'\
                  '第2フェイズから、近鉄への転換が可能になります。第2フェイズ下期になると、近鉄に強制転換されます。',
            sym: '大軌',
            type: :minor,
            abilities: [{ type: 'no_buy', owner_type: 'player' },
                        { type: 'exchange',
                          corporations: ['近鉄'],
                          when: 'or_between_turns',
                          from: 'reserved'},
                        { type: 'shares', shares: '近鉄_0' },
                       ],
            color: nil,
          },
          {
            name: '大阪鉄道',
            value: 100,
            revenue: 0,
            desc: '近鉄の株1株に引き替えて閉鎖します。閉鎖時に全資産を近鉄は引き継ぎます。'\
                  '近鉄が設立されたら、強制実行されます。',
            sym: '阪鉄',
            type: :minor,
            abilities: [{ type: 'no_buy', owner_type: 'player' }                       ],
            color: nil,
          },
          {
            name: '奈良電鉄',
            value: 160,
            revenue: 0,
            desc: '第4フェイズから近鉄への合併が可能になり、第5フェイズに強制合併します。',
            sym: '奈良',
            type: :minor,
            abilities: [{ type: 'no_buy', owner_type: 'player' }],
            color: nil,
          },
          {
            name: '神戸電鉄',
            value: 100,
            revenue: 0,
            desc: '運営ラウンド中に後発会社へ転換できます。',
            sym: '神戸',
            type: :minor,
            abilities: [{ type: 'no_buy', owner_type: 'player' }],
            color: nil,
          },


        ].freeze

        CORPORATIONS = [
          {
            float_percent: 50,
            sym: '南海',
            name: '南海電気鉄道',
            type: 'major',
            logo: '1890/南海',
            simple_logo: '1889/AR.alt',
            tokens: [0, 40, 100],
            coordinates: 'I12',
            color: '#006633',
          },
          {
            float_percent: 40,
            sym: '京阪',
            name: '京阪急行鉄道',
            type: 'major',
            logo: '1889/IR',
            simple_logo: '1889/IR.alt',
            tokens: [0, 40, 100],
            coordinates: 'E16',
            color: '#005a3c',
          },
          {
            float_percent: 50,
            sym: '山陽',
            name: '山陽電鉄',
            type: 'major',
            logo: '1889/SR',
            simple_logo: '1889/SR.alt',
            tokens: [0, 40],
            coordinates: 'F3',
            color: '#c51e2f',
          },
          {
            float_percent: 40,
            sym: '阪神',
            name: '阪神電気鉄道',
            type: 'major',
            logo: '1889/KO',
            simple_logo: '1889/KO.alt',
            tokens: [0, 40, 100],
            coordinates: 'F9',
            color: '#004F8A',
          },
          {
            float_percent: 50,
            sym: '阪急',
            name: '阪急電鉄',
            type: 'major',
            logo: '1889/TR',
            simple_logo: '1889/TR.alt',
            tokens: [0, 40, 100, 100],
            coordinates: 'E12',
            color: '#6A3437',
          },
          {
            sym: '近鉄',
            name: '近畿鉄道',
            type: 'major',
            logo: '1889/TR',
            simple_logo: '1889/TR.alt',
            tokens: [0, 40, 100, 100,100,100],
            floatable: false,
            float_percent: 20,
            color: '#6A3437',
          },
          {
            float_percent: 50,
            sym: 'JR',
            name: 'JR',
            type: 'national',
            logo: '1889/KU',
            simple_logo: '1889/KU.alt',
            tokens: [0, 0, 0, 0,40,100],
            coordinates: %w[F5],
            abilities: [
              { type: 'reservation', hex: 'G12', city: 0 },
              { type: 'reservation', hex: 'B17', city: 0 },
              { type: 'reservation', hex: 'H19', city: 1 },
            ],

            color: '#6A3437',
          },
          {
            float_percent: 50,
            sym: 'メトロ',
            name: '大阪地下鉄',
            type: 'major',
            logo: '1824/SR',
            simple_logo: '1889/SR.alt',
            tokens: [0],
            coordinates: 'H11',

            color: '#6A3437',
          },
        ].freeze

        MINORS = [
          {
            name: '河南鉄道',
            sym: '河南',
            type: 'minor',
            logo: '1824/C1',
            tokens: [0],
            coordinates: 'J15',
            color: '#F58220',
            text_color: 'black',
          },
          {
            name: '大阪電気軌道',
            sym: '大軌',
            type: 'minor',
            logo: '1824/C2',
            tokens: [0],
            coordinates: 'H13',
            color: '#F7A1F1F',
            text_color: 'black',
          },
          {
            name: '大阪鉄道',
            sym: '阪鉄',
            type: 'minor',
            logo: '1824/C3',
            color: '#F7A1F1F',
            text_color: 'black',
            tokens: [],
          },
          {
            name: '奈良電鉄',
            sym: '奈良',
            type: 'minor',
            logo: '1824/C4',
            tokens: [0, 0],
            coordinates: %w[B17 H19],
            abilities: [
              { type: 'reservation', hex: 'B17', city: 1 },
              { type: 'reservation', hex: 'H19', city: 0 },
            ],
            color: '#8B4513',
            text_color: 'white',
          },
          {
            name: '神戸電鉄',
            sym: '神戸',
            type: 'minor',
            logo: '1824/C4',
            tokens: [0],
            coordinates: 'D5',
            color: '#4169E1',
            text_color: 'white',
          },
        ].freeze
      end
    end
  end
end
